const MAX_SIZE = 4096;
const ZIP_LIMIT = 30;
const MULTI_DOWNLOAD_LIMIT = 10;
const MULTI_DOWNLOAD_INTERVAL_MS = 500;
const RESIZE_METHODS = [
  ["containNatural", "元画像の縦横比を使用"], ["stretch", "変形"], ["cover", "トリミング"], ["pad", "余白付与"]
];
const BATCH_RESIZE_METHODS = [["stretch", "変形"], ["cover", "トリミング"], ["pad", "余白付与"]];
const PRESETS = [
  { name: "アイコン 512", w: 512, h: 512, cat: "アイコン", common: true },
  { name: "アイコン 192", w: 192, h: 192, cat: "アイコン", common: true },
  { name: "正方形 1080", w: 1080, h: 1080, cat: "SNS", common: true },
  { name: "SNS縦 1080x1350", w: 1080, h: 1350, cat: "SNS", common: true },
  { name: "ストーリー 1080x1920", w: 1080, h: 1920, cat: "SNS", common: true },
  { name: "HD 1280x720", w: 1280, h: 720, cat: "動画", common: true },
  { name: "Full HD 1920x1080", w: 1920, h: 1080, cat: "動画", common: true },
  { name: "OGP 1200x630", w: 1200, h: 630, cat: "ブログ / Web", common: true },
  { name: "ブログ 800x450", w: 800, h: 450, cat: "ブログ / Web", common: true },
  { name: "Pixel壁紙", w: 1080, h: 2400, cat: "スマホ壁紙", common: false },
  { name: "iPhone壁紙", w: 1290, h: 2796, cat: "スマホ壁紙", common: false },
  { name: "A4比率", w: 1240, h: 1754, cat: "その他", common: false }
];
const RATIOS = [["", "縦横比指定なし"], ["original", "元画像比率"], ["1:1", "1:1"], ["4:3", "4:3"], ["3:4", "3:4"], ["3:2", "3:2"], ["2:3", "2:3"], ["16:9", "16:9"], ["9:16", "9:16"], ["4:5", "4:5"], ["5:4", "5:4"], ["21:9", "21:9"]];
const state = {
  top: "single", singleMode: "resize", singleResizeMethod: "containNatural", singleCropDirection: "both", cropRatio: "",
  single: { original: null, working: null, fileName: "image", x: 0.5, y: 0.5, matte: "transparent" },
  batch: { mode: "resize", method: "stretch", files: [], index: 0, x: 0.5, y: 0.5, matte: "transparent" }
};
const $ = (id) => document.getElementById(id);
function setMessage(text, error) { const el = $("message"); el.textContent = text || ""; el.classList.toggle("error", Boolean(error)); }
function show(el, visible) { el.classList.toggle("hidden", !visible); }
function ratioOf(w, h) { return w / h; }
function closeRatio(a, b) { return Math.abs(a - b) < 0.015; }
function parseRatio(value, img) { if (!value) return null; if (value === "original") return img ? img.width / img.height : null; const p = value.split(":").map(Number); return p[0] / p[1]; }
function imageSource(img) { return img.image || img; }
function baseName(name) { return (name || "image").replace(/\.[^.]+$/, "").replace(/[^a-zA-Z0-9_-]+/g, "_"); }
function ext(type) { return type === "image/jpeg" ? "jpg" : type === "image/webp" ? "webp" : "png"; }
function quality(type, selectId) { return type === "image/png" ? undefined : Number($(selectId).value); }
function fillMatte(ctx, w, h, matte, type) { if (matte === "transparent" && type !== "image/jpeg") { ctx.clearRect(0, 0, w, h); return; } ctx.fillStyle = matte === "black" ? "#000" : "#fff"; ctx.fillRect(0, 0, w, h); }
function validateSize(w, h) { if (!w || !h) throw new Error("幅と高さを入力してください。"); if (!Number.isInteger(w) || !Number.isInteger(h)) throw new Error("幅と高さは整数で入力してください。"); if (w < 1 || h < 1) throw new Error("幅と高さは1以上で入力してください。"); if (w > MAX_SIZE || h > MAX_SIZE) throw new Error("幅と高さは4096px以下で入力してください。"); }
function readSize(wId, hId) { const w = Number($(wId).value); const h = Number($(hId).value); validateSize(w, h); return { w, h }; }
function loadImageFromFile(file) { return new Promise((resolve, reject) => { if (!/^image\/(png|jpeg|webp)$/.test(file.type)) { reject(new Error("対応していない画像形式です。")); return; } const url = URL.createObjectURL(file); const img = new Image(); img.onload = () => resolve({ image: img, width: img.naturalWidth, height: img.naturalHeight, fileName: file.name, url }); img.onerror = () => reject(new Error("画像の読み込みに失敗しました。")); img.src = url; }); }
function drawConvert(img, w, h, mode, opts, type) { const canvas = document.createElement("canvas"); canvas.width = w; canvas.height = h; const ctx = canvas.getContext("2d"); const src = imageSource(img); const sw = img.width, sh = img.height; const matte = opts.matte || "transparent"; if (mode === "pad" || mode === "cropNoScale") fillMatte(ctx, w, h, matte, type); else if (type === "image/jpeg") fillMatte(ctx, w, h, "white", type); if (mode === "stretch") ctx.drawImage(src, 0, 0, w, h); if (mode === "containNatural") { const s = Math.min(w / sw, h / sh); const dw = Math.round(sw * s), dh = Math.round(sh * s); ctx.drawImage(src, 0, 0, dw, dh); }
  if (mode === "cover" || mode === "pad") { const s = mode === "cover" ? Math.max(w / sw, h / sh) : Math.min(w / sw, h / sh); const dw = sw * s, dh = sh * s; const dx = (w - dw) * opts.x; const dy = (h - dh) * opts.y; ctx.drawImage(src, dx, dy, dw, dh); }
  if (mode === "cropNoScale") { const sx = Math.max(0, (sw - w) * opts.x), sy = Math.max(0, (sh - h) * opts.y); const sWidth = Math.min(sw, w), sHeight = Math.min(sh, h); const dx = Math.max(0, (w - sw) * opts.x), dy = Math.max(0, (h - sh) * opts.y); ctx.drawImage(src, sx, sy, sWidth, sHeight, dx, dy, sWidth, sHeight); }
  return canvas; }
function blobFromCanvas(canvas, type, q) { return new Promise((resolve, reject) => canvas.toBlob((b) => b ? resolve(b) : reject(new Error("このブラウザは選択した保存形式に対応していません。PNGで保存してください。")), type, q)); }
function downloadBlob(blob, name) { const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); }
function renderChoices(containerId, items, current, cb) { const box = $(containerId); box.textContent = ""; items.forEach(([value, label]) => { const b = document.createElement("button"); b.type = "button"; b.textContent = label; b.className = value === current ? "active" : ""; b.addEventListener("click", () => cb(value)); box.appendChild(b); }); }
function renderPosition(id, axes, target) { const box = $(id); box.textContent = ""; if (!axes.length) return; const labels = { x: [[0, "左"], [0.5, "中央"], [1, "右"]], y: [[0, "上"], [0.5, "中央"], [1, "下"]] }; axes.forEach((axis) => { const row = document.createElement("div"); row.className = "position-row"; const title = document.createElement("strong"); title.textContent = axis === "x" ? "横方向" : "縦方向"; row.appendChild(title); labels[axis].forEach(([v, label]) => { const b = document.createElement("button"); b.type = "button"; b.textContent = label; b.className = Math.abs(target[axis] - v) < 0.01 ? "active" : ""; b.addEventListener("click", () => { target[axis] = v; saveSettings(); renderAll(); }); row.appendChild(b); }); box.appendChild(row); }); }
function renderMatte(id, visible, target) { const box = $(id); box.textContent = ""; if (!visible) return; const row = document.createElement("div"); row.className = "position-row"; const s = document.createElement("strong"); s.textContent = "余白色"; row.appendChild(s); [["transparent", "透明"], ["white", "白"], ["black", "黒"]].forEach(([v, label]) => { const b = document.createElement("button"); b.type = "button"; b.textContent = label; b.className = target.matte === v ? "active" : ""; b.addEventListener("click", () => { target.matte = v; saveSettings(); renderAll(); }); row.appendChild(b); }); box.appendChild(row); }
function filteredPresets(kind) { const img = state.single.working; if (kind === "singleResize" && state.singleResizeMethod === "containNatural" && img) return PRESETS.filter((p) => closeRatio(p.w / p.h, img.width / img.height)); if (kind === "singleCrop" && img) { const r = parseRatio(state.cropRatio, img); return PRESETS.filter((p) => (state.singleCropDirection !== "vertical" || p.w === img.width) && (state.singleCropDirection !== "horizontal" || p.h === img.height) && (!r || closeRatio(p.w / p.h, r))); } return PRESETS; }
function renderPresets(id, kind, wId, hId) { const box = $(id); box.textContent = ""; const presets = filteredPresets(kind); const common = presets.filter((p) => p.common); const wrap = document.createElement("div"); wrap.className = "preset-group"; const title = document.createElement("h3"); title.textContent = "よく使うサイズ"; wrap.appendChild(title); const list = document.createElement("div"); list.className = "preset-buttons"; common.forEach((p) => list.appendChild(presetButton(p, wId, hId))); wrap.appendChild(list); box.appendChild(wrap); if (!presets.length) { const p = document.createElement("p"); p.className = "notice"; p.textContent = "元画像の縦横比に合うプリセットがありません。幅または高さを直接入力してください。"; box.appendChild(p); return; } [...new Set(presets.map((p) => p.cat))].forEach((cat) => { const d = document.createElement("details"); d.className = "preset-group"; const s = document.createElement("summary"); s.textContent = cat; d.appendChild(s); const buttons = document.createElement("div"); buttons.className = "preset-buttons"; presets.filter((p) => p.cat === cat).forEach((p) => buttons.appendChild(presetButton(p, wId, hId))); d.appendChild(buttons); box.appendChild(d); }); }
function presetButton(p, wId, hId) { const b = document.createElement("button"); b.type = "button"; b.textContent = `${p.name} ${p.w}×${p.h}`; b.addEventListener("click", () => { $(wId).value = p.w; $(hId).value = p.h; saveSettings(); renderAll(); }); return b; }
function outputForSingle() { if (!state.single.working) throw new Error("画像が選択されていません。"); if (state.singleMode === "resize") { const size = readSize("singleResizeWidth", "singleResizeHeight"); const map = { containNatural: "containNatural", stretch: "stretch", cover: "cover", pad: "pad" }; return { img: state.single.working, w: size.w, h: size.h, mode: map[state.singleResizeMethod], cropName: false, opts: state.single }; } const size = readSize("singleCropWidth", "singleCropHeight"); return { img: state.single.working, w: size.w, h: size.h, mode: "cropNoScale", cropName: true, opts: state.single }; }
function drawPreview(canvasId, textId, output, type) { const canvas = $(canvasId); const preview = drawConvert(output.img, output.w, output.h, output.mode, output.opts, type); const max = 900; const scale = Math.min(1, max / Math.max(output.w, output.h)); canvas.width = Math.max(1, Math.round(output.w * scale)); canvas.height = Math.max(1, Math.round(output.h * scale)); const ctx = canvas.getContext("2d"); ctx.drawImage(preview, 0, 0, canvas.width, canvas.height); $(textId).textContent = `出力：${output.w} × ${output.h}`; }
function renderSingle() { show($("singleResizePanel"), state.singleMode === "resize"); show($("singleCropPanel"), state.singleMode === "crop"); $("singleResizeBtn").classList.toggle("active", state.singleMode === "resize"); $("singleCropBtn").classList.toggle("active", state.singleMode === "crop"); renderChoices("singleResizeMethod", RESIZE_METHODS, state.singleResizeMethod, (v) => { state.singleResizeMethod = v; saveSettings(); renderAll(); }); const img = state.single.working; $("singleInfo").textContent = img ? `作業中：${img.fileName} / ${img.width}×${img.height}` : ""; const rw = Number($("singleResizeWidth").value), rh = Number($("singleResizeHeight").value); $("singleResizeNote").textContent = state.singleResizeMethod === "stretch" && img && rw && rh && !closeRatio(rw / rh, img.width / img.height) ? "縦横比が変わるため、画像が歪む場合があります。" : ""; renderPresets("singleResizePresets", "singleResize", "singleResizeWidth", "singleResizeHeight"); const axes = state.singleResizeMethod === "cover" || state.singleResizeMethod === "pad" ? cropAxes(img, rw, rh, state.singleResizeMethod) : []; renderPosition("singleResizePosition", axes, state.single); renderMatte("singleResizeMatte", state.singleResizeMethod === "pad", state.single); renderPresets("singleCropPresets", "singleCrop", "singleCropWidth", "singleCropHeight"); renderPosition("singleCropPosition", state.singleCropDirection === "both" ? ["x", "y"] : state.singleCropDirection === "vertical" ? ["y"] : ["x"], state.single); const cw = Number($("singleCropWidth").value), ch = Number($("singleCropHeight").value); renderMatte("singleCropMatte", img && (cw > img.width || ch > img.height), state.single); renderNudge("singleNudge", state.singleMode === "crop" ? (state.singleCropDirection === "both" ? ["x", "y"] : state.singleCropDirection === "vertical" ? ["y"] : ["x"]) : axes, state.single); try { if (img) drawPreview("singlePreview", "singlePreviewText", outputForSingle(), $("singleFormat").value); } catch (e) { $("singlePreviewText").textContent = e.message; } }
function cropAxes(img, w, h, mode) { if (!img || !w || !h) return ["x", "y"]; const diff = mode === "cover" ? img.width / img.height < w / h : img.width / img.height > w / h; return diff ? ["y"] : ["x"]; }
function renderNudge(id, axes, target) { const box = $(id); box.textContent = ""; if (!axes.length) return; [[0.08, "通常"], [0.02, "微調整"]].forEach(([step, label]) => { const row = document.createElement("div"); row.className = "position-row"; const strong = document.createElement("strong"); strong.textContent = label; row.appendChild(strong); [["x", -step, "←"], ["x", step, "→"], ["y", -step, "↑"], ["y", step, "↓"]].filter((x) => axes.includes(x[0])).forEach(([axis, delta, mark]) => { const b = document.createElement("button"); b.type = "button"; b.textContent = mark; b.addEventListener("click", () => { target[axis] = Math.max(0, Math.min(1, target[axis] + delta)); renderAll(); }); row.appendChild(b); }); box.appendChild(row); }); }
function renderBatch() { $("batchResizeBtn").classList.toggle("active", state.batch.mode === "resize"); $("batchCropBtn").classList.toggle("active", state.batch.mode === "crop"); $("batchDesc").textContent = state.batch.mode === "resize" ? "一括リサイズでは変形・トリミング・余白付与を共通設定で適用します。" : "元画像を拡大縮小せず、切り抜きまたは余白付与で出力範囲を作ります。"; renderChoices("batchResizeMethod", BATCH_RESIZE_METHODS, state.batch.method, (v) => { state.batch.method = v; saveSettings(); renderAll(); }); show($("batchResizeMethod"), state.batch.mode === "resize"); renderPresets("batchPresets", "batch", "batchWidth", "batchHeight"); const pos = state.batch.mode === "crop" || ["cover", "pad"].includes(state.batch.method); renderPosition("batchPosition", pos ? ["x", "y"] : [], state.batch); renderMatte("batchMatte", state.batch.mode === "crop" || state.batch.method === "pad", state.batch); $("batchInfo").textContent = state.batch.files.length ? `選択枚数：${state.batch.files.length}` : ""; $("batchPager").textContent = state.batch.files.length ? `${state.batch.index + 1} / ${state.batch.files.length}` : "0 / 0"; try { const out = outputForBatch(state.batch.files[state.batch.index]); if (out) drawPreview("batchPreview", "batchPreviewText", out, $("batchFormat").value); } catch (e) { $("batchPreviewText").textContent = e.message; } }
function outputForBatch(img) { if (!img) return null; const size = readSize("batchWidth", "batchHeight"); return { img, w: size.w, h: size.h, mode: state.batch.mode === "crop" ? "cropNoScale" : state.batch.method, cropName: state.batch.mode === "crop", opts: state.batch }; }
function renderFormat() { show($("singleQualityLabel"), $("singleFormat").value !== "image/png"); show($("batchQualityLabel"), $("batchFormat").value !== "image/png"); }
function renderAll() { renderFormat(); renderSingle(); renderBatch(); }
function saveSettings() { localStorage.setItem("singleSettings", JSON.stringify({ mode: state.singleMode, method: state.singleResizeMethod, cropDirection: state.singleCropDirection, ratio: state.cropRatio })); localStorage.setItem("batchSettings", JSON.stringify({ mode: state.batch.mode, method: state.batch.method })); localStorage.setItem("commonSettings", JSON.stringify({ singleFormat: $("singleFormat")?.value, batchFormat: $("batchFormat")?.value })); }
function applyCropHelpers(changed) { const img = state.single.working; if (!img) return; const dir = $("cropDirection").value; state.singleCropDirection = dir; state.cropRatio = $("cropRatio").value; const r = parseRatio(state.cropRatio, img); if (dir === "vertical") { $("singleCropWidth").value = img.width; $("singleCropWidth").disabled = true; if (r) { $("singleCropHeight").value = Math.round(img.width / r); $("singleCropHeight").disabled = true; } else $("singleCropHeight").disabled = false; } else if (dir === "horizontal") { $("singleCropHeight").value = img.height; $("singleCropHeight").disabled = true; if (r) { $("singleCropWidth").value = Math.round(img.height * r); $("singleCropWidth").disabled = true; } else $("singleCropWidth").disabled = false; } else { $("singleCropWidth").disabled = false; $("singleCropHeight").disabled = false; if (r && changed === "w") $("singleCropHeight").value = Math.round(Number($("singleCropWidth").value) / r); if (r && changed === "h") $("singleCropWidth").value = Math.round(Number($("singleCropHeight").value) * r); } }
async function saveSingle(continueOnly) { const out = outputForSingle(); const type = $("singleFormat").value; const canvas = drawConvert(out.img, out.w, out.h, out.mode, out.opts, type); if (continueOnly) { const img = new Image(); img.src = canvas.toDataURL("image/png"); await img.decode(); state.single.working = { image: img, width: canvas.width, height: canvas.height, fileName: state.single.fileName }; renderAll(); return; } const blob = await blobFromCanvas(canvas, type, quality(type, "singleQuality")); downloadBlob(blob, `${baseName(state.single.fileName)}${out.cropName ? "_crop" : ""}_${out.w}x${out.h}.${ext(type)}`); }
async function batchSave(zip) { if (!state.batch.files.length) throw new Error("画像が選択されていません。"); if (zip && state.batch.files.length > ZIP_LIMIT) throw new Error("ZIP保存は最大30枚までです。"); if (!zip && state.batch.files.length > MULTI_DOWNLOAD_LIMIT) throw new Error("連続ダウンロードは最大10枚までです。枚数が多い場合はZIP保存を使ってください。"); const type = $("batchFormat").value; if (zip) { const z = new JSZip(); for (const img of state.batch.files) { const out = outputForBatch(img); const blob = await blobFromCanvas(drawConvert(out.img, out.w, out.h, out.mode, out.opts, type), type, quality(type, "batchQuality")); z.file(`${baseName(img.fileName)}_${out.w}x${out.h}.${ext(type)}`, blob); } const today = new Date().toISOString().slice(0, 10).replace(/-/g, ""); downloadBlob(await z.generateAsync({ type: "blob" }), `converted_images_${today}.zip`); } else { for (let i = 0; i < state.batch.files.length; i++) { const out = outputForBatch(state.batch.files[i]); const blob = await blobFromCanvas(drawConvert(out.img, out.w, out.h, out.mode, out.opts, type), type, quality(type, "batchQuality")); setTimeout(() => downloadBlob(blob, `${baseName(out.img.fileName)}_${out.w}x${out.h}.${ext(type)}`), i * MULTI_DOWNLOAD_INTERVAL_MS); } } }
function bind() { $("singleTopBtn").onclick = () => { state.top = "single"; show($("singleSection"), true); show($("batchSection"), false); $("singleTopBtn").classList.add("active"); $("batchTopBtn").classList.remove("active"); }; $("batchTopBtn").onclick = () => { state.top = "batch"; show($("singleSection"), false); show($("batchSection"), true); $("batchTopBtn").classList.add("active"); $("singleTopBtn").classList.remove("active"); };
  $("singleResizeBtn").onclick = () => { state.singleMode = "resize"; saveSettings(); renderAll(); }; $("singleCropBtn").onclick = () => { state.singleMode = "crop"; saveSettings(); renderAll(); }; $("batchResizeBtn").onclick = () => { state.batch.mode = "resize"; saveSettings(); renderAll(); }; $("batchCropBtn").onclick = () => { state.batch.mode = "crop"; saveSettings(); renderAll(); };
  $("singleFile").onchange = async (e) => { try { const img = await loadImageFromFile(e.target.files[0]); state.single.original = img; state.single.working = img; state.single.fileName = img.fileName; $("singleResizeWidth").value = img.width; $("singleResizeHeight").value = img.height; $("singleCropWidth").value = img.width; $("singleCropHeight").value = img.height; renderAll(); } catch (err) { setMessage(err.message, true); } };
  $("batchFiles").onchange = async (e) => { try { state.batch.files = await Promise.all([...e.target.files].map(loadImageFromFile)); state.batch.index = 0; if (state.batch.files[0]) { $("batchWidth").value = state.batch.files[0].width; $("batchHeight").value = state.batch.files[0].height; } renderAll(); } catch (err) { setMessage(err.message, true); } };
  $("batchPrev").onclick = () => { state.batch.index = Math.max(0, state.batch.index - 1); renderAll(); }; $("batchNext").onclick = () => { state.batch.index = Math.min(state.batch.files.length - 1, state.batch.index + 1); renderAll(); };
  ["singleResizeWidth", "singleResizeHeight"].forEach((id) => $(id).addEventListener("input", () => { if (state.singleResizeMethod === "containNatural" && state.single.working) { const img = state.single.working; if (id.endsWith("Width")) $("singleResizeHeight").value = Math.round(Number($(id).value) * img.height / img.width); else $("singleResizeWidth").value = Math.round(Number($(id).value) * img.width / img.height); } saveSettings(); renderAll(); }));
  ["singleCropWidth", "singleCropHeight"].forEach((id) => $(id).addEventListener("input", () => { applyCropHelpers(id.endsWith("Width") ? "w" : "h"); saveSettings(); renderAll(); })); $("cropDirection").onchange = () => { applyCropHelpers(); saveSettings(); renderAll(); }; $("cropRatio").onchange = () => { applyCropHelpers("w"); saveSettings(); renderAll(); };
  ["singleFormat", "batchFormat", "singleQuality", "batchQuality", "batchWidth", "batchHeight"].forEach((id) => $(id).addEventListener("input", () => { saveSettings(); renderAll(); }));
  $("singleSaveBtn").onclick = () => saveSingle(false).catch((e) => setMessage(e.message || "保存に失敗しました。もう一度お試しください。", true)); $("continueBtn").onclick = () => saveSingle(true).catch((e) => setMessage(e.message, true)); $("resetOriginalBtn").onclick = () => { if (state.single.original) state.single.working = state.single.original; renderAll(); };
  $("zipSaveBtn").onclick = () => batchSave(true).catch((e) => setMessage(e.message || "ZIP保存に失敗しました。枚数を減らして再度お試しください。", true)); $("multiDownloadBtn").onclick = () => batchSave(false).catch((e) => setMessage(e.message, true));
  let drag = null; $("singlePreview").addEventListener("pointerdown", (e) => { drag = { x: e.clientX, y: e.clientY, sx: state.single.x, sy: state.single.y }; }); window.addEventListener("pointermove", (e) => { if (!drag) return; state.single.x = Math.max(0, Math.min(1, drag.sx + (e.clientX - drag.x) / 200)); state.single.y = Math.max(0, Math.min(1, drag.sy + (e.clientY - drag.y) / 200)); renderAll(); }); window.addEventListener("pointerup", () => { drag = null; }); }
function init() { RATIOS.forEach(([v, label]) => { const o = document.createElement("option"); o.value = v; o.textContent = label; $("cropRatio").appendChild(o); }); bind(); renderAll(); if ("serviceWorker" in navigator) navigator.serviceWorker.register("service-worker.js"); }
init();
